/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { CuboidCollider, RigidBody } from "@react-three/rapier";

export default function Fox(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/fox.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Idle.reset().fadeIn(0.5).play();
    return () => {
      actions.Idle.fadeOut(0.5);
    };
  }, [actions]);

  return (
    <RigidBody type="fixed" name="Fox" {...props} colliders={false}>
      <group ref={group} dispose={null} rotation-y={Math.PI}>
        <group name="Scene">
          <group
            name="Idle"
            position={[0, 0.339, 0]}
            rotation={[0.094, -Math.PI / 2, 0]}
            scale={0.01}
          >
            <skinnedMesh
              name="Fox_Mesh"
              geometry={nodes.Fox_Mesh.geometry}
              material={materials.Fox}
              skeleton={nodes.Fox_Mesh.skeleton}
            />
            <primitive object={nodes.Fox_Pelvis} />
          </group>
        </group>
      </group>
      <CuboidCollider args={[0.2, 0.5, 0.2]} position={[0, 0.5, 0]} />
    </RigidBody>
  );
}

useGLTF.preload("/fox.glb");
