/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/fox.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Rolling.reset().fadeIn(0.5).play();
    return () => {
      actions.Rolling.fadeOut(0.5);
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Idle"
          position={[0, 0.339, 0]}
          rotation={[0.094, -Math.PI / 2, 0]}
          scale={0.01}
        >
          <skinnedMesh
            name="Fox_Mesh"
            geometry={nodes.Fox_Mesh.geometry}
            material={materials.Fox}
            skeleton={nodes.Fox_Mesh.skeleton}
          />
          <primitive object={nodes.Fox_Pelvis} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/fox.glb");
